### ISSUE TITLE
Kurulumun Readme dosyasına eklenilmesi

### ISSUE THREAD

**Issue by alisanalacam** [enesaltinok/observability#1]
Kurulum aşamasını readme dosyasında anlatımının yapılması.

**Comment by alisanalacam** [comment]
@enesaltinok sıfırdan kurulumun yapılmasını anlatabilir misiniz?
"docker-compose up" yeterli oluyor mu?
 ayrıca java projesi için yapmamız gerekenleri de yazabilir misiniz?

**Comment by alisanalacam** [comment]
build_java_application.sh dosyasını görmemiştim. şimdi gördüm:)

**Comment by enesaltinok** [comment]
Gerekli güncelleme yapılmıştır.
